// ─── Shared ML configuration constants ──────────────────────────────────────
// Single source of truth for all thresholds, defaults, and magic numbers.
// Import in mlWorker.ts and MLAnalysis.tsx instead of hardcoding values.

export const ML_CONFIG = {
  // ── Data validation ──
  MIN_DATA_POINTS: 100,
  MIN_VALID_ROWS: 50,
  MAX_SPEED: 300,

  // ── Timestep ──
  DEFAULT_DT: 0.016,
  FALLBACK_TIMESTAMP_MS: 16,

  // ── Tire Wear ──
  TIRE_WEAR_INITIAL_LIFE: 100,
  TIRE_WEAR_HEURISTIC_SCALE: 0.00002,
  TIRE_WEAR_ONNX_OUTPUT_IDX: 0,

  // ── Fatigue ──
  FATIGUE_MIN_POINTS: 100,
  FATIGUE_SEGMENTS: 4,
  FATIGUE_SMOOTHNESS_SCALE: 50,
  FATIGUE_DECAY_SCALE: 200,
  FATIGUE_IMPROVEMENT_THRESH: 0.02,

  // ── Safety Score ──
  SAFETY_DEDUP_WINDOW: 3,
  SAFETY_JERK_X_THRESH: 15,
  SAFETY_JERK_Y_THRESH: 10,
  SAFETY_PEDAL_OVERLAP_THRESH: 0.15,
  SAFETY_UNDERSTEER_THRESH: 0.5,
  SAFETY_OVERSTEER_THRESH: 0.5,
  SAFETY_BRAKE_DELTA_THRESH: -0.3,
  SAFETY_PENALTY_NORMALIZE_DIVISOR: 10,
  SAFETY_SCORE_MULTIPLIER: 40,

  // ── State Clustering ──
  NUM_STATES: 4,
  STATE_ERRATIC_JERK_THRESH: 15,
  STATE_CORNERING_G_THRESH: 1.2,
  STATE_CORNERING_SPEED_THRESH: 20,
  STATE_SLOW_SPEED_THRESH: 10,
  STATE_NORMALIZE_EPSILON: 1,

  // ── Anomaly Detection ──
  ANOMALY_SIGMA_MULTIPLIER: 4,
  ANOMALY_G_FORCE_FLOOR: 2.0,
  ANOMALY_G_FORCE_OFFSET: 1.5,
  ANOMALY_DOWNSAMPLE_STEP: 1,
  ANOMALY_SPEED_THRESH: 160,
  ANOMALY_HARSH_BRAKE_ACCEL: -5,
  ANOMALY_HARSH_ACCEL_ACCEL: 5,

  // ── PCA Heuristic ──
  PCA_HEURISTIC_JERK_SCALE: 5,
  PCA_HEURISTIC_JERK_OFFSET: -2,
  PCA_HEURISTIC_G_SCALE: 3,
  PCA_HEURISTIC_G_OFFSET: -1,

  // ── Shifts ──
  SHIFT_EARLY_RPM: 4000,
  SHIFT_LATE_RPM: 7200,
  SHIFT_DEFAULT_OPTIMAL: 1,
  SHIFT_ONNX_EARLY_BOUND: 1.5,
  SHIFT_ONNX_OPTIMAL_BOUND: 2.5,

  // ── Pedal Overlap ──
  PEDAL_OVERLAP_ONNX_THRESH: 0.5,
  PEDAL_OVERLAP_HEURISTIC_THRESH: 0.03,

  // ── Corner Exit Forecast ──
  EXIT_WINDOW_STEP: 20,
  EXIT_ACCEL_THRESH: 2,
  EXIT_STEERING_THRESH: 0.2,
  EXIT_DEFAULT_SPEED_COEFF: 0.5,
  EXIT_DEFAULT_THROTTLE_COEFF: 0.2,
  EXIT_MIN_SAMPLES: 3,
  EXIT_DETERMINANT_EPSILON: 1e-10,
  EXIT_RIDGE_LAMBDA: 0.1,

  // ── Brake Zones ──
  BRAKE_ZONE_PRESSURE_THRESH: 20,
  BRAKE_ZONE_MIN_LENGTH: 10,
  BRAKE_ZONE_DEFAULT_DTW: 85.5,

  // ── Braking Technique ──
  BRAKE_TECH_PRESSURE_THRESH: 10,
  BRAKE_TECH_STEERING_DELTA: 0.05,

  // ── KNN Archetypes ──
  KNN_ARCHETYPES: [
    { x: -14, y: -3, label: 'Smooth Professional' },
    { x: -4, y: 2, label: 'Cautious Amateur' },
    { x: 8, y: -2, label: 'Aggressive Amateur' },
    { x: 18, y: 8, label: 'Erratic Novice' },
  ] as const,

  // ── Quality Metrics Fallbacks ──
  QUALITY_FALLBACK_PCA_VARIANCE: 0.72,
  QUALITY_FALLBACK_RF_R2: 0.78,
  QUALITY_FALLBACK_SILHOUETTE_HIGH: 0.65,
  QUALITY_FALLBACK_SILHOUETTE_LOW: 0.35,
  QUALITY_ERRATIC_PCT_THRESH: 15,
  QUALITY_REGRESSION_BAND_HIGH: 80,
  QUALITY_REGRESSION_BAND_MID: 50,
  QUALITY_REGRESSION_SCORE_HIGH: 0.72,
  QUALITY_REGRESSION_SCORE_MID: 0.55,
  QUALITY_REGRESSION_SCORE_LOW: 0.35,
  QUALITY_GRIP_BAND_HIGH: 80,
  QUALITY_GRIP_BAND_MID: 50,
  QUALITY_DT_PURITY_HIGH: 0.65,
  QUALITY_DT_PURITY_MID: 0.45,
  QUALITY_DT_PURITY_LOW: 0.3,
  QUALITY_SVM_MIN_SCORE: 0.3,
  QUALITY_ANOMALY_DENSITY_SCALE: 10,
  QUALITY_NB_ACCURACY_BONUS: 0.1,

  // ── Performance ──
  ONNX_CHUNK_SIZE: 100,
  MAX_CHART_POINTS: 2000,
  ANALYSIS_TIMEOUT_MS: 120000,
};

export type MLConfig = typeof ML_CONFIG;
